### ISSUE TITLE
No documentation on correlation between BatchPostingLimit and Period settings

### ISSUE THREAD

**Issue by xantari** [serilog/serilog-sinks-email#45]
It appears batch posting limit is set to 100 by default with null period setting.

What does that mean exactly? It will wait until 100 log messages have occurred before email is sent?

What if a time period of say 1 minute is set?

Does that mean if 100 errors occur within 1 minute it will send an email, but if 99 errors occur in 1 minute it will NOT send an email?

Very confusing as to what role these two settings play, and how they interact with each other.

**Comment by dougkwilson** [comment]
In [LoggerConfigurationEmailExtensions](https://github.com/serilog/serilog-sinks-email/blob/dev/src/Serilog.Sinks.Email/LoggerConfigurationEmailExtensions.cs#L196) the null is replaced with a default value of 30 seconds.

`var defaultedPeriod = period ?? EmailSink.DefaultPeriod;`

So 99 log entries will be sent after 30 seconds elapse.  If 100 entries they will be sent immediately.

I'm not clear on what happens if 101 events are logged.  The first 100 will be sent immediately but I don't know what will happen with the remaining event.  The [code is here](https://github.com/serilog/serilog-sinks-periodicbatching/blob/89f21b0caec0ec2bb2f0b5233b123061b8483bc6/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs#L150) if you want to take a look.

Please correct me if I'm wrong.

**Comment by augustoproiete** [comment]
@xantari @hellfirehd See if this helps:

**[In Serilog Email Sink, what is relation between batchPostingLimit and period?](https://stackoverflow.com/a/61548730/211672)**

**Comment by nblumhardt** [comment]
Closing this one as stale, hope you were able to find the info you needed.
